// Silent audio with paced output. Generated by ChatGPT.
//
// A backend with no device: periods pass at the nominal rate on the
// monotonic clock, output is discarded and input is silence. Built in,
// so the transport runs on a machine with no audio at all (tests, VMs)
// and the engine still has one master port to pace it.
#ifndef SSM_DUMMY_AUDIO_H
#define SSM_DUMMY_AUDIO_H
#include "AudioClient.h"
namespace spiralcore
{
class DummyClient: public AudioClient
{
	bool attached;
	unsigned frames;
	unsigned rate;
	unsigned inChannels;
	unsigned outChannels;
	double period;
	double next;
	AudioCycleTiming timing;

public:
	DummyClient();
	virtual bool Attach(const std::string &device, const AudioClientOptions &opt);
	virtual void Detach();
	virtual bool IsAttached() const { return attached; }
	virtual int WaitForCycle(unsigned milliseconds);
	virtual unsigned long GetBufferSize() const { return frames; }
	virtual unsigned long GetSampleRate() const { return rate; }
	virtual bool GetCycleTiming(AudioCycleTiming &) const;
	virtual bool Write(const float *interleaved, unsigned int nframes);
	virtual bool Read(float *interleaved, unsigned int nframes);
};
}
#endif
