// RtMidi is confined to this loadable backend. Generated by ChatGPT.
#include "BackendModule.h"
#include "MidiBackend.h"
#include <RtMidi.h>
#include <atomic>
#include <thread>
#include <mutex>
#include <chrono>
#include <memory>
#include <algorithm>
using namespace Spiral;
// One producer/consumer per queue. Overflow requests a note reset, never blocks DSP.
class PacketQueue
{
	MidiPacket packets[1024];
	std::atomic<unsigned> read, write;

public:
	PacketQueue():
	    read(0),
	    write(0)
	{
	}
	bool Push(const MidiPacket &p)
	{
		unsigned w= write.load(std::memory_order_relaxed), n= (w + 1) % 1024;
		if(n == read.load(std::memory_order_acquire))
			return false;
		packets[w]= p;
		write.store(n, std::memory_order_release);
		return true;
	}
	bool Pop(MidiPacket &p)
	{
		unsigned r= read.load(std::memory_order_relaxed);
		if(r == write.load(std::memory_order_acquire))
			return false;
		p= packets[r];
		read.store((r + 1) % 1024, std::memory_order_release);
		return true;
	}
};
class RtMidiBackend: public MidiBackend
{
	PacketQueue incoming, outgoing;
	std::atomic<bool> stop, inputOverflow, outputOverflow;
	std::atomic<unsigned> epoch;
	std::mutex mutex;
	std::string source, destination, status;
	std::vector<std::string> inputs, outputs;
	bool sent[16][128]= {};
	std::thread worker;
	void Panic(RtMidiOut &out)
	{
		// Release only this instance's notes; other MIDI devices may share the destination.
		for(unsigned c= 0; c < 16; ++c)
			for(unsigned n= 0; n < 128; ++n)
				if(sent[c][n])
				{
					if(out.isPortOpen())
					{
						std::vector<unsigned char> p= {(unsigned char)(0x80 + c), (unsigned char)n, 0};
						out.sendMessage(&p);
					}
					sent[c][n]= false;
				}
	}
	void Run()
	{
		while(!stop.load())
		{
			try
			{
				RtMidiIn in(RtMidi::UNSPECIFIED, "SSM MIDI input", 1024);
				RtMidiOut out(RtMidi::UNSPECIFIED, "SSM MIDI output");
				in.ignoreTypes(true, false, false);
				unsigned active= ~0u;
				std::string oldSource, oldDestination;
				unsigned ticks= 0;
				while(!stop.load())
				{
					std::string src, dst;
					unsigned desired;
					{
						std::lock_guard<std::mutex> lock(mutex);
						src= source;
						dst= destination;
						desired= epoch.load();
					}
					if(active != desired || ++ticks >= 500)
					{
						ticks= 0;
						std::vector<std::string> ins, outs;
						for(unsigned i= 0; i < in.getPortCount(); ++i)
							ins.push_back(in.getPortName(i));
						for(unsigned i= 0; i < out.getPortCount(); ++i)
							outs.push_back(out.getPortName(i));
						bool inputLost= !oldSource.empty() && std::find(ins.begin(), ins.end(), oldSource) == ins.end();
						bool outputLost= !oldDestination.empty() && std::find(outs.begin(), outs.end(), oldDestination) == outs.end();
						if(active != desired || inputLost || outputLost)
						{
							Panic(out);
							in.closePort();
							out.closePort();
							active= desired;
							oldSource.clear();
							oldDestination.clear();
							inputOverflow.store(true);
						}
						if(!in.isPortOpen() && !src.empty())
							for(unsigned i= 0; i < ins.size(); ++i)
								if(ins[i] == src)
								{
									in.openPort(i, "SSM input");
									oldSource= src;
									break;
								}
						if(!out.isPortOpen() && !dst.empty())
							for(unsigned i= 0; i < outs.size(); ++i)
								if(outs[i] == dst)
								{
									out.openPort(i, "SSM output");
									oldDestination= dst;
									break;
								}
						std::lock_guard<std::mutex> lock(mutex);
						inputs= ins;
						outputs= outs;
						status= (!src.empty() && !in.isPortOpen()) ? "MIDI source unavailable" : (!dst.empty() && !out.isPortOpen()) ? "MIDI destination unavailable" :
																			       "MIDI ready";
					}
					if(outputOverflow.exchange(false))
						Panic(out);
					MidiPacket p;
					while(outgoing.Pop(p))
						if(p.Epoch == active && out.isPortOpen())
						{
							std::vector<unsigned char> bytes;
							bytes.push_back(p.Status);
							if(p.Status < 0xf0)
							{
								bytes.push_back(p.Data1);
								if((p.Status & 0xe0) != 0xc0)
									bytes.push_back(p.Data2);
							}
							out.sendMessage(&bytes);
							if(p.Data1 < 128 && ((p.Status & 0xf0) == 0x90 || (p.Status & 0xf0) == 0x80))
								sent[p.Status & 15][p.Data1]= (p.Status & 0xf0) == 0x90 && p.Data2 != 0;
						}
					std::vector<unsigned char> bytes;
					for(unsigned n= 0; n < 256; ++n)
					{
						in.getMessage(&bytes);
						if(bytes.empty())
							break;
						if(bytes[0] < 0x80 || (bytes[0] >= 0xf0 && bytes[0] < 0xf8))
							continue;
						p= MidiPacket(bytes[0], bytes.size() > 1 ? bytes[1] : 0, bytes.size() > 2 ? bytes[2] : 0);
						p.Epoch= active;
						if(!incoming.Push(p))
							inputOverflow.store(true);
					}
					std::this_thread::sleep_for(std::chrono::milliseconds(2));
				}
				Panic(out);
			}
			catch(const std::exception &e)
			{
				std::lock_guard<std::mutex> lock(mutex);
				status= e.what();
				inputs.clear();
				outputs.clear();
				inputOverflow.store(true);
			}
			// Backend creation can fail when the MIDI service is absent; retry without affecting DSP loading.
			for(int n= 0; n < 50 && !stop.load(); ++n)
				std::this_thread::sleep_for(std::chrono::milliseconds(20));
		}
	}

public:
	RtMidiBackend():
	    stop(false),
	    inputOverflow(false),
	    outputOverflow(false),
	    epoch(0),
	    status("Starting MIDI"),
	    worker(&RtMidiBackend::Run, this)
	{
	}
	~RtMidiBackend()
	{
		stop.store(true);
		worker.join();
	}
	std::vector<std::string> Ports(bool output)
	{
		std::lock_guard<std::mutex> lock(mutex);
		return output ? outputs : inputs;
	}
	void Select(const std::string &s, const std::string &d)
	{
		std::lock_guard<std::mutex> lock(mutex);
		if(s != source || d != destination)
		{
			source= s;
			destination= d;
			epoch.fetch_add(1);
		}
	}
	bool Poll(MidiPacket &p)
	{
		if(inputOverflow.exchange(false))
		{
			for(unsigned n= 0; n < 1024 && incoming.Pop(p); ++n)
			{
			}
			p= MidiPacket(0xff);
			return true;
		}
		for(unsigned n= 0; n < 1024 && incoming.Pop(p); ++n)
			if(p.Epoch == epoch.load())
				return true;
		return false;
	}
	bool Send(const MidiPacket &p)
	{
		MidiPacket copy= p;
		copy.Epoch= epoch.load();
		if(outgoing.Push(copy))
			return true;
		outputOverflow.store(true);
		return false;
	}
	std::string Status()
	{
		std::lock_guard<std::mutex> lock(mutex);
		return status;
	}
};
static void *Create(void *)
{
	try
	{
		return new RtMidiBackend;
	}
	catch(...)
	{
		return NULL;
	}
}
static void Destroy(void *p)
{
	delete(MidiBackend *)p;
}
extern "C" const Spiral::BackendDescriptor *SSM_Backend_v1()
{
	static const Spiral::BackendDescriptor d= {1, "midi", "rtmidi", Create, Destroy};
	return &d;
}
