// Versioned backend module boundary. Generated by ChatGPT.
//
// One descriptor shape serves every backend kind: a module exports a
// function returning it, a compiled-in backend registers it directly.
// Kind names the registry it belongs to ("audio", "midi"); each kind
// defines its own ABI number and Create/Destroy types.
#ifndef SSM_BACKEND_MODULE_H
#define SSM_BACKEND_MODULE_H
namespace spiralcore
{
	struct BackendDescriptor
	{
		unsigned ABI;
		const char *Kind, *Name;
		void *(*Create)(void *context);
		void (*Destroy)(void *instance);
	};
} // namespace spiralcore
#endif
