// Native MIDI worker regressions without a hardware service. Generated by ChatGPT.
#include "NativeMidi.h"
#include <cassert>
#include <functional>
#include <iostream>
#include <stdexcept>
using namespace Spiral;
static void Wait(const std::function<bool()> &f)
{
	auto limit= std::chrono::steady_clock::now() + std::chrono::seconds(3);
	while(!f())
	{
		assert(std::chrono::steady_clock::now() < limit);
		std::this_thread::sleep_for(std::chrono::milliseconds(2));
	}
}
struct State
{
	MidiQueue input;
	std::atomic<bool> service{false}, link{true}, closed{false};
	std::atomic<unsigned> opens{0}, connects{0};
	std::mutex mutex;
	std::vector<std::pair<std::string, MidiPacket>> sent;
	bool Has(const std::string &dst, unsigned status, unsigned note)
	{
		std::lock_guard<std::mutex> lock(mutex);
		for(auto &p: sent) if(p.first == dst && p.second.Status == status && p.second.Data1 == note) return true;
		return false;
	}
};
class Fake: public MidiTransport
{
	std::shared_ptr<State> state;
	std::string destination;
public:
	explicit Fake(std::shared_ptr<State> s): state(s) {}
	void Open() { ++state->opens; if(!state->service) throw std::runtime_error("service absent"); }
	void Close() { state->closed= true; }
	bool Alive() const { return state->service; }
	std::vector<std::string> Ports(bool out) { return out ? std::vector<std::string>{"one", "two"} : std::vector<std::string>{"keys"}; }
	bool Connect(const std::string &, const std::string &dst) { destination= dst; ++state->connects; return state->link; }
	bool Connected() { return state->link; }
	bool Read(MidiPacket &p) { return state->input.Pop(p); }
	bool Write(const MidiPacket &p)
	{
		if(!state->link || destination.empty()) return false;
		std::lock_guard<std::mutex> lock(state->mutex);
		state->sent.emplace_back(destination, p);
		return true;
	}
	std::string Status() const { return state->link ? "ready" : "disconnected"; }
};
int main()
{
	assert(MidiSize(0x90) == 3 && MidiSize(0xc0) == 2 && MidiSize(0xd0) == 2 && MidiSize(0xf8) == 1);
	assert(!ValidMidi(MidiPacket(0xf0)) && !ValidMidi(MidiPacket(0x90, 128, 0)));
	MidiQueue q; MidiPacket p;
	for(unsigned n= 0; n < 1023; ++n) assert(q.Push(MidiPacket(0x90, n % 128, 1)));
	assert(!q.Push(MidiPacket()));
	for(unsigned n= 0; n < 1023; ++n) { assert(q.Pop(p)); assert(p.Data1 == n % 128); }
	assert(!q.Pop(p));
	auto state= std::make_shared<State>();
	{
		NativeMidiBackend backend(new Fake(state));
		backend.Select("keys", "one");
		Wait([&] { return state->opens > 0; });
		assert(!backend.Send(MidiPacket(0x90, 60, 100)));
		state->service= true;
		Wait([&] { return backend.Status() == "ready" && state->connects > 0; });
		while(backend.Poll(p)) {}
		assert(state->input.Push(MidiPacket(0x90, 62, 90)));
		Wait([&] { return backend.Poll(p) && p.Status == 0x90; });
		assert(p.Data1 == 62 && p.Data2 == 90);
		assert(backend.Send(MidiPacket(0x90, 60, 100)));
		Wait([&] { return state->Has("one", 0x90, 60); });
		backend.Select("keys", "two");
		Wait([&] { return state->Has("one", 0x80, 60); });
		Wait([&] { return state->connects >= 2; });
		Wait([&] { return backend.Send(MidiPacket(0x90, 65, 100)); });
		Wait([&] { return state->Has("two", 0x90, 65); });
		assert(!state->Has("two", 0x90, 60));
		state->link= false;
		Wait([&] { return backend.Status() == "disconnected"; });
		assert(!backend.Send(MidiPacket(0x90, 67, 100)));
		while(backend.Poll(p)) {}
		state->link= true;
		Wait([&] { return backend.Status() == "ready"; });
		Wait([&] { return backend.Send(MidiPacket(0x90, 69, 100)); });
		Wait([&] { return state->Has("two", 0x90, 69); });
		assert(backend.Send(MidiPacket(0xb0, 64, 127)));
		Wait([&] { return state->Has("two", 0xb0, 64); });
	}
	assert(state->closed && state->Has("two", 0x80, 69));
	std::cout << "Native MIDI queue, retry, bidirectional packets, selection cleanup and disconnect PASS\n";
}
