// Native MIDI worker regressions without a hardware service. Generated by ChatGPT.
#include "NativeMidi.h"
#include <cassert>
#include <iostream>
#include <stdexcept>
#include <sched.h>
using namespace Spiral;
#define WaitUntil(condition)                                                    \
	do                                                                      \
	{                                                                       \
		const double limit = SSMCompat::MonotonicMilliseconds() + 3000; \
		while (!(condition))                                            \
		{                                                               \
			assert(SSMCompat::MonotonicMilliseconds() < limit);     \
			SSMCompat::SleepMilliseconds(2);                        \
		}                                                               \
	} while (0)

struct State
{
	MidiQueue input;
	SSMCompat::Atomic<bool> service, link, closed;
	SSMCompat::Atomic<unsigned> opens, connects;

	State():
	    service(false),
	    link(true),
	    closed(false),
	    opens(0),
	    connects(0)
	{
	}

	SSMCompat::Mutex mutex;
	std::vector<std::pair<std::string, MidiPacket> > sent;

	bool Has(const std::string &dst, unsigned status, unsigned note)
	{
		SSMCompat::Lock lock(mutex);
		{
			std::vector<std::pair<std::string, MidiPacket> > &range1 = sent;
			for (std::vector<std::pair<std::string, MidiPacket> >::iterator entry1 = range1.begin(); entry1 != range1.end(); ++entry1)
			{
				std::vector<std::pair<std::string, MidiPacket> >::value_type &p = *entry1;
				if (p.first == dst && p.second.Status == status && p.second.Data1 == note)
					return true;
			}
		}
		return false;
	}
};

class Fake: public MidiTransport
{
	State *state;
	std::string destination;

public:
	explicit Fake(State *s):
	    state(s)
	{
	}

	void Open()
	{
		state->opens.fetch_add(1);
		if (!state->service.load())
			throw std::runtime_error("service absent");
	}

	void Close()
	{
		state->closed.store(true);
	}

	bool Alive() const
	{
		return state->service.load();
	}

	std::vector<std::string> Ports(bool out)
	{
		std::vector<std::string> names;
		names.push_back(out ? "one" : "keys");
		if (out)
			names.push_back("two");
		return names;
	}

	bool Connect(const std::string &, const std::string &dst)
	{
		destination = dst;
		state->connects.fetch_add(1);
		return state->link.load();
	}

	bool Connected()
	{
		return state->link.load();
	}

	bool Read(MidiPacket &p)
	{
		return state->input.Pop(p);
	}

	bool Write(const MidiPacket &p)
	{
		if (!state->link.load() || destination.empty())
			return false;
		SSMCompat::Lock lock(state->mutex);
		state->sent.push_back(std::make_pair(destination, p));
		return true;
	}

	std::string Status() const
	{
		return state->link.load() ? "ready" : "disconnected";
	}
};

static void *ProducePackets(void *data)
{
	MidiQueue &queue = *static_cast<MidiQueue *>(data);
	for (unsigned i = 0; i < 100000; ++i)
	{
		MidiPacket packet(0x90, i % 128, (i / 128) % 128);
		packet.Epoch = i;
		while (!queue.Push(packet))
			sched_yield();
	}
	return NULL;
}

int main()
{
	assert(MidiSize(0x90) == 3 && MidiSize(0xc0) == 2 && MidiSize(0xd0) == 2 && MidiSize(0xf8) == 1);
	assert(!ValidMidi(MidiPacket(0xf0)) && !ValidMidi(MidiPacket(0x90, 128, 0)));
	MidiQueue q;
	MidiPacket p;
	for (unsigned n = 0; n < 1023; ++n)
		assert(q.Push(MidiPacket(0x90, n % 128, 1)));
	assert(!q.Push(MidiPacket()));
	for (unsigned n = 0; n < 1023; ++n)
	{
		assert(q.Pop(p));
		assert(p.Data1 == n % 128);
	}
	assert(!q.Pop(p));
	pthread_t producer;
	assert(pthread_create(&producer, NULL, ProducePackets, &q) == 0);
	for (unsigned i = 0; i < 100000; ++i)
	{
		while (!q.Pop(p))
			sched_yield();
		assert(p.Epoch == i && p.Status == 0x90 && p.Data1 == i % 128 && p.Data2 == (i / 128) % 128);
	}
	assert(pthread_join(producer, NULL) == 0);

	State storage;
	State *state = &storage;
	{
		NativeMidiBackend backend(new Fake(state));
		backend.Select("keys", "one");
		WaitUntil(state->opens.load() > 0);
		assert(!backend.Send(MidiPacket(0x90, 60, 100)));
		state->service.store(true);
		WaitUntil(backend.Status() == "ready" && state->connects.load() > 0);
		while (backend.Poll(p))
		{
		}
		assert(state->input.Push(MidiPacket(0x90, 62, 90)));
		WaitUntil(backend.Poll(p) && p.Status == 0x90);
		assert(p.Data1 == 62 && p.Data2 == 90);
		assert(backend.Send(MidiPacket(0x90, 60, 100)));
		WaitUntil(state->Has("one", 0x90, 60));
		backend.Select("keys", "two");
		WaitUntil(state->Has("one", 0x80, 60));
		WaitUntil(state->connects.load() >= 2);
		WaitUntil(backend.Send(MidiPacket(0x90, 65, 100)));
		WaitUntil(state->Has("two", 0x90, 65));
		assert(!state->Has("two", 0x90, 60));
		state->link.store(false);
		WaitUntil(backend.Status() == "disconnected");
		assert(!backend.Send(MidiPacket(0x90, 67, 100)));
		while (backend.Poll(p))
		{
		}
		state->link.store(true);
		WaitUntil(backend.Status() == "ready");
		WaitUntil(backend.Send(MidiPacket(0x90, 69, 100)));
		WaitUntil(state->Has("two", 0x90, 69));
		assert(backend.Send(MidiPacket(0xb0, 64, 127)));
		WaitUntil(state->Has("two", 0xb0, 64));
	}
	assert(state->closed.load() && state->Has("two", 0x80, 69));
	std::cout << "Native MIDI queue, retry, bidirectional packets, selection cleanup and disconnect PASS\n";
}
