// Generated by ChatGPT; hardware ownership stays within this module.
#include "BackendModule.h"
#include "AudioBackend.h"
#include "ESDClient.h"
static void *Create(void *data)
{
	AudioBackendContext *c= (AudioBackendContext *)data;
	ESDClient::host= c->Host;
	ESDClient::RunCallback= c->Run;
	ESDClient::RunContext= c->User;
	return new OutputAudioClientAdapter<ESDClient>(ESDClient::Get());
}
static void Destroy(void *p)
{
	delete(OutputAudioClientBackend *)p;
}
extern "C" const Spiral::BackendDescriptor *SSM_Backend_v1()
{
	static const Spiral::BackendDescriptor d= {1, "audio", "esd", Create, Destroy};
	return &d;
}
