// Generated by ChatGPT; hardware ownership stays within this module.
#include "BackendModule.h"
#include "AudioBackend.h"
#include "PipeWireClient.h"
static void *Create(void *data)
{
	AudioBackendContext *c= (AudioBackendContext *)data;
	PipeWireClient::host= c->Host;
	PipeWireClient::RunCallback= c->Run;
	PipeWireClient::RunContext= c->User;
	return new OutputAudioClientAdapter<PipeWireClient>(PipeWireClient::Get());
}
static void Destroy(void *p)
{
	delete(OutputAudioClientBackend *)p;
}
extern "C" const Spiral::BackendDescriptor *SSM_Backend_v1()
{
	static const Spiral::BackendDescriptor d= {1, "audio", "pipewire", Create, Destroy};
	return &d;
}
