// Versioned audio module boundary. Generated by ChatGPT.
//
// A backend creates AudioClients of one native kind (portaudio, jack,
// coreaudio...). It lives either in a module exporting
// SpiralPlugin_GetAudioBackend(), or compiled in and registered at
// startup; the registry hands out clients by name either way, so the
// host never names a native implementation. The descriptor is shared
// with the private tree; its Kind lets one shape serve audio and midi.
#ifndef SSM_BACKEND_MODULE_H
#define SSM_BACKEND_MODULE_H
#include <string>
#include <vector>
#include <map>
#include "AudioClient.h"
#include "PluginLoader.h"
namespace spiralcore
{
	// Bumped when AudioClient or the descriptor changes shape; the registry
	// refuses backends built against another version.
#define SPIRAL_AUDIO_PLUGIN_ABI 1
	struct BackendDescriptor
	{
		unsigned ABI;
		const char *Kind, *Name;
		void *(*Create)(void *context);
		void (*Destroy)(void *instance);
	};
	// The audio kind: modules are <plugins>/audio/<Backend>/<Backend>_Audio<ext>.
	// Compiled-in backends register their descriptor directly; modules arrive
	// through Accept. The first registration of a name wins. Handles stay with
	// the PluginLoader; destroy instances before unloading.
	class AudioBackendRegistry : public PluginKind
	{
	public:
		static AudioBackendRegistry *Get();
		static void PackUpAndGoHome();
		void Register(const BackendDescriptor *);
		unsigned LoadModules(const std::string &root);
		const BackendDescriptor *Find(const std::string &) const;
		// Registration order, which is the preference when no backend is
		// named, except that the dummy always comes last: it is the backend
		// of last resort, whenever it was registered.
		std::vector<std::string> Names() const;
		AudioClient *Create(const std::string &name);
		void Destroy(const std::string &name, AudioClient *client);

		// PluginKind
		virtual const char *Name() const { return "audio"; }
		virtual const char *Subdirectory() const { return "audio"; }
		virtual const char *Suffix() const { return "_Audio"; }
		virtual const char *EntrySymbol() const { return "SpiralPlugin_GetAudioBackend"; }
		virtual bool Accept(void *entry, const std::string &path);
		virtual bool CanUnload() const { return clients.empty(); }
		virtual void Release(void *entry, const std::string &path);

	private:
		AudioBackendRegistry();
		~AudioBackendRegistry();
		std::vector<const BackendDescriptor *> entries;
		std::map<AudioClient *, const BackendDescriptor *> clients;
		static AudioBackendRegistry *m_Singleton;
		AudioBackendRegistry(const AudioBackendRegistry &);
		AudioBackendRegistry &operator=(const AudioBackendRegistry &);
	};
	// Built in and always present.
	const BackendDescriptor *DummyBackend();
} // namespace spiralcore
extern "C"
{
	// The one symbol an audio backend module exports.
	typedef const spiralcore::BackendDescriptor *(*SpiralPlugin_GetAudioBackendFn)();
}
#endif
