// Versioned audio/MIDI module boundary. Generated by ChatGPT.
#ifndef SSM_BACKEND_MODULE_H
#define SSM_BACKEND_MODULE_H
#include <string>
#include <map>
#include <vector>
namespace Spiral
{
	void SetDeviceDefaults(const std::map<std::string,std::string> &);
	std::string DeviceDefault(const std::string &, const std::string &fallback);
	void SetAudioBackendDefaults(const std::string &, const std::string &);
	std::string DefaultAudioBackend();
	std::string DefaultAudioDestination();
	struct BackendDescriptor
	{
		unsigned ABI;
		const char *Kind, *Name;
		void *(*Create)(void *context);
		void (*Destroy)(void *instance);
	};
	// Handles remain loaded while the registry lives; destroy instances first.
	class BackendRegistry
	{
	public:
		explicit BackendRegistry(const std::string &kind);
		~BackendRegistry();
		const BackendDescriptor *Find(const std::string &) const;
		std::vector<std::string> Names() const;

	private:
		std::vector<void *> handles;
		std::vector<const BackendDescriptor *> entries;
		void Scan(const std::string &, const std::string &);
		BackendRegistry(const BackendRegistry &);
		BackendRegistry &operator=(const BackendRegistry &);
	};
} // namespace Spiral
#endif
