// Silent audio with paced output. Generated by ChatGPT.
#ifndef SSM_DUMMY_AUDIO_H
#define SSM_DUMMY_AUDIO_H
#include "AudioBackend.h"
#include <time.h>
#include <errno.h>
class DummyAudioBackend: public OutputAudioClientBackend
{
	Patch *host;
	float volume;

public:
	explicit DummyAudioBackend(Patch *p):
	    host(p),
	    volume(.5)
	{
	}
	void AllocateBuffer() {}
	void DeallocateBuffer() {}
	void SendStereo(InputPort *, InputPort *) {}
	void GetStereo(OutputPort *l, OutputPort *r)
	{
		if(l)
			l->GetSampleBuffer(0)->Zero();
		if(r)
			r->GetSampleBuffer(0)->Zero();
	}
	void SetVolume(FloatType v) { volume= v; }
	FloatType GetVolume() { return volume; }
	void SetNumChannels(int) {}
	void SetDestination(const std::string &) {}
	void Play()
	{
		if(host && host->SampleRate())
        {
            const unsigned long long microseconds=1000000ULL * host->SampleCount() / host->SampleRate();
            struct timespec delay;
            delay.tv_sec=microseconds / 1000000;
            delay.tv_nsec=(microseconds % 1000000) * 1000;
            while(nanosleep(&delay,&delay) != 0 && errno == EINTR) {}
        }
	}
	void Read() {}
	bool OpenReadWrite() { return true; }
	bool OpenWrite() { return true; }
	bool OpenRead() { return true; }
	bool Close() { return true; }
};
#endif
