// Hardware-free MIDI contract. Generated by ChatGPT.
#ifndef SSM_MIDI_BACKEND_H
#define SSM_MIDI_BACKEND_H
#include <string>
#include <vector>
namespace Spiral
{
	struct MidiPacket
	{
		unsigned char Status, Data1, Data2;
		unsigned Epoch;
		MidiPacket(unsigned char s= 0, unsigned char a= 0, unsigned char b= 0):
		    Status(s),
		    Data1(a),
		    Data2(b),
		    Epoch(0)
		{
		}
	};
	class MidiBackend
	{
	public:
		virtual ~MidiBackend() {}
		virtual std::vector<std::string> Ports(bool output)= 0;
		virtual void Select(const std::string &source, const std::string &destination)= 0;
		virtual bool Poll(MidiPacket &)= 0;
		virtual bool Send(const MidiPacket &)= 0;
		virtual std::string Status()= 0;
	};
	class DummyMidiBackend: public MidiBackend
	{
	public:
		std::vector<std::string> Ports(bool) { return std::vector<std::string>(); }
		void Select(const std::string &, const std::string &) {}
		bool Poll(MidiPacket &) { return false; }
		bool Send(const MidiPacket &) { return true; }
		std::string Status() { return "Dummy MIDI (no hardware)"; }
	};
} // namespace Spiral
#endif
