// Hardware-free MIDI contract. Generated by ChatGPT.
//
// A backend moves three-byte MIDI packets between the synth and some
// transport (ALSA sequencer, JACK MIDI, CoreMIDI, RtMidi...). It lives
// either in a module exporting SpiralPlugin_GetMidiBackend(), or
// compiled in and registered at startup; the registry hands out
// backends by name either way. The descriptor is the one in
// BackendModule.h, with Kind "midi".
#ifndef SSM_MIDI_BACKEND_H
#define SSM_MIDI_BACKEND_H
#include <string>
#include <vector>
#include <map>
#include "BackendModule.h"
#include "PluginLoader.h"
namespace spiralcore
{
	struct MidiPacket
	{
		unsigned char Status, Data1, Data2;
		unsigned Epoch;
		MidiPacket(unsigned char s= 0, unsigned char a= 0, unsigned char b= 0):
		    Status(s),
		    Data1(a),
		    Data2(b),
		    Epoch(0)
		{
		}
	};
	class MidiBackend
	{
	public:
		virtual ~MidiBackend() {}
		virtual std::vector<std::string> Ports(bool output)= 0;
		virtual void Select(const std::string &source, const std::string &destination)= 0;
		// Never blocks: the synth thread polls once per cycle.
		virtual bool Poll(MidiPacket &)= 0;
		virtual bool Send(const MidiPacket &)= 0;
		virtual std::string Status()= 0;
	};
	class DummyMidiBackend: public MidiBackend
	{
	public:
		std::vector<std::string> Ports(bool) { return std::vector<std::string>(); }
		void Select(const std::string &, const std::string &) {}
		bool Poll(MidiPacket &) { return false; }
		bool Send(const MidiPacket &) { return true; }
		std::string Status() { return "Dummy MIDI (no hardware)"; }
	};

	// Bumped when MidiBackend or the descriptor changes shape; the registry
	// refuses backends built against another version.
#define SPIRAL_MIDI_PLUGIN_ABI 1
	// The midi kind: modules are <plugins>/midi/<Backend>/<Backend>_Midi<ext>.
	// Compiled-in backends register their descriptor directly; modules
	// arrive through Accept. The first registration of a name wins.
	class MidiBackendRegistry : public PluginKind
	{
	public:
		static MidiBackendRegistry *Get();
		static void PackUpAndGoHome();
		void Register(const BackendDescriptor *);
		unsigned LoadModules(const std::string &root);
		const BackendDescriptor *Find(const std::string &) const;
		// Registration order, which is the preference when no backend is
		// named, except that the dummy always comes last.
		std::vector<std::string> Names() const;
		MidiBackend *Create(const std::string &name);
		void Destroy(const std::string &name, MidiBackend *backend);

		// PluginKind
		virtual const char *Name() const { return "midi"; }
		virtual const char *Subdirectory() const { return "midi"; }
		virtual const char *Suffix() const { return "_Midi"; }
		virtual const char *EntrySymbol() const { return "SpiralPlugin_GetMidiBackend"; }
		virtual bool Accept(void *entry, const std::string &path);
		virtual bool CanUnload() const { return backends.empty(); }
		virtual void Release(void *entry, const std::string &path);

	private:
		MidiBackendRegistry();
		~MidiBackendRegistry();
		std::vector<const BackendDescriptor *> entries;
		std::map<MidiBackend *, const BackendDescriptor *> backends;
		static MidiBackendRegistry *m_Singleton;
		MidiBackendRegistry(const MidiBackendRegistry &);
		MidiBackendRegistry &operator=(const MidiBackendRegistry &);
	};
	// Built in and always present.
	const BackendDescriptor *DummyMidi();
} // namespace spiralcore
extern "C"
{
	// The one symbol a midi backend module exports.
	typedef const spiralcore::BackendDescriptor *(*SpiralPlugin_GetMidiBackendFn)();
}
#endif
