// Native MIDI worker/transport boundary. Generated by ChatGPT.
// SPDX-License-Identifier: GPL-2.0-or-later
#ifndef SSM_NATIVE_MIDI_H
#define SSM_NATIVE_MIDI_H
#include "MidiBackend.h"
#include <memory>
#include "ThreadCompatibility.h"
#include "Compatibility.h"

namespace spiralcore
{
// Exactly one producer and one consumer. Neither side allocates or locks.
class MidiQueue
{
	MidiPacket packets[1024];
	SSMCompat::Atomic<unsigned> read, write;
public:
	MidiQueue():read(0),write(0) {}
	bool Push(const MidiPacket &packet)
	{
		unsigned w= write.load(SSMCompat::Relaxed), next= (w + 1) % 1024;
		if(next == read.load(SSMCompat::Acquire)) return false;
		packets[w]= packet;
		write.store(next, SSMCompat::Release);
		return true;
	}
	bool Peek(MidiPacket &packet)
	{
		unsigned r= read.load(SSMCompat::Relaxed);
		if(r == write.load(SSMCompat::Acquire)) return false;
		packet= packets[r];
		return true;
	}
	bool Pop(MidiPacket &packet)
	{
		if(!Peek(packet)) return false;
		read.store((read.load(SSMCompat::Relaxed) + 1) % 1024, SSMCompat::Release);
		return true;
	}
};

inline unsigned MidiSize(unsigned char status)
{
	if(status < 0x80) return 0;
	if(status < 0xf0) return (status & 0xe0) == 0xc0 ? 2 : 3;
	// Fixed-packet contract: channel voice and defined realtime messages only.
	return status == 0xf8 || status == 0xfa || status == 0xfb ||
	       status == 0xfc || status == 0xfe || status == 0xff ? 1 : 0;
}
inline bool ValidMidi(const MidiPacket &p)
{
	unsigned size= MidiSize(p.Status);
	return size && (size < 2 || p.Data1 < 128) && (size < 3 || p.Data2 < 128);
}

// All methods run on the worker, never the synth thread. JACK internally
// bridges its process callback with a second pair of fixed packet queues.
class MidiTransport
{
public:
	virtual ~MidiTransport() {}
	virtual void Open()= 0;
	virtual void Close()= 0;
	virtual bool Alive() const= 0;
	virtual std::vector<std::string> Ports(bool output)= 0;
	virtual bool Connect(const std::string &, const std::string &)= 0;
	virtual bool Connected()= 0;
	virtual bool Read(MidiPacket &)= 0;
	virtual bool Write(const MidiPacket &)= 0;
	virtual bool Flush() { return true; }
	virtual bool LostInput() { return false; }
	virtual std::string Status() const= 0;
};

class NativeMidiBackend: public MidiBackend
{
	std::auto_ptr<MidiTransport> transport;
	MidiQueue incoming, outgoing;
	SSMCompat::Atomic<bool> stop, reset, overflow, ready;
	SSMCompat::Atomic<unsigned> epoch;
	SSMCompat::Mutex mutex;
	std::string source, destination, status;
	std::vector<std::string> inputs, outputs;
	bool notes[16][128];
	bool sustain[16];
	pthread_t worker;
	static void *Worker(void *);
	void Run();
	void Panic();
	void Track(const MidiPacket &);
public:
	explicit NativeMidiBackend(MidiTransport *);
	~NativeMidiBackend();
	std::vector<std::string> Ports(bool output);
	void Select(const std::string &, const std::string &);
	bool Poll(MidiPacket &);
	bool Send(const MidiPacket &);
	std::string Status();
};
}
#endif
