// Generated by ChatGPT. Backend modules alone link hardware API libraries.
#include "AudioBackend.h"
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <iostream>
#include <algorithm>
namespace spiralcore
{
	// Backends still compiled into libspiralcore register here; each moves
	// out to Plugins/Audio in its own change and its line leaves that list.
	void RegisterBuiltinAudioBackends(AudioBackendRegistry *registry);

	AudioBackendRegistry *AudioBackendRegistry::m_Singleton= NULL;
	AudioBackendRegistry *AudioBackendRegistry::Get()
	{
		if(!m_Singleton)
		{
			m_Singleton= new AudioBackendRegistry;
			RegisterBuiltinAudioBackends(m_Singleton);
		}
		PluginManager::Get()->RegisterKind(m_Singleton);
		return m_Singleton;
	}
	void AudioBackendRegistry::PackUpAndGoHome()
	{
		if (!m_Singleton || !m_Singleton->CanUnload())
			return;

		PluginManager::Get()->UnregisterKind(m_Singleton);
		delete m_Singleton;
		m_Singleton= NULL;
	}
	AudioBackendRegistry::AudioBackendRegistry()
	{
	}
	void AudioBackendRegistry::Register(const BackendDescriptor *d)
	{
		if(!d || !d->Kind || std::string(Name()) != d->Kind || !d->Name || !*d->Name || !d->Create || !d->Destroy || Find(d->Name))
			return;
		if(d->ABI != SPIRAL_AUDIO_PLUGIN_ABI)
		{
			std::cerr << "audio backend '" << d->Name << "': ABI " << d->ABI
			          << ", host has " << SPIRAL_AUDIO_PLUGIN_ABI << "; ignored" << std::endl;
			return;
		}
		entries.push_back(d);
	}
	unsigned AudioBackendRegistry::LoadModules(const std::string &root)
	{
		return PluginManager::Get()->Load(*this, root);
	}
	bool AudioBackendRegistry::Accept(void *entry, const std::string &)
	{
		const BackendDescriptor *d= ((SpiralPlugin_GetAudioBackendFn)entry)();
		if(!d || !d->Name)
			return false;
		// A compiled-in backend of the same name keeps its place.
		if(Find(d->Name))
			return false;
		Register(d);
		return Find(d->Name) == d;
	}
	void AudioBackendRegistry::Release(void *entry, const std::string &)
	{
		const BackendDescriptor *d = ((SpiralPlugin_GetAudioBackendFn)entry)();
		entries.erase(std::remove(entries.begin(), entries.end(), d), entries.end());
	}

	AudioBackendRegistry::~AudioBackendRegistry()
	{
	}
	const BackendDescriptor *AudioBackendRegistry::Find(const std::string &name) const
	{
		for(size_t i= 0; i < entries.size(); ++i)
			if(name == entries[i]->Name)
				return entries[i];
		return NULL;
	}
	std::vector<std::string> AudioBackendRegistry::Names() const
	{
		std::vector<std::string> n;
		bool dummy= false;
		for(size_t i= 0; i < entries.size(); ++i)
		{
			if(std::string(entries[i]->Name) == "dummy")
				dummy= true;
			else
				n.push_back(entries[i]->Name);
		}
		if(dummy)
			n.push_back("dummy");
		return n;
	}
	AudioClient *AudioBackendRegistry::Create(const std::string &name)
	{
		const BackendDescriptor *d= Find(name);
		AudioClient *client = d ? static_cast<AudioClient *>(d->Create(NULL)) : NULL;
		if (client)
			clients[client] = d;

		return client;
	}
	void AudioBackendRegistry::Destroy(const std::string &name, AudioClient *client)
	{
		std::map<AudioClient *, const BackendDescriptor *>::iterator found = clients.find(client);
		if (found == clients.end() || name != found->second->Name)
			return;

		const BackendDescriptor *d = found->second;
		clients.erase(found);
		d->Destroy(client);
	}
} // namespace spiralcore
