// Generated by ChatGPT. Backend modules alone link hardware API libraries.
#include "BackendModule.h"
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <dirent.h>
#include <dlfcn.h>
#include <cstdlib>
#include <algorithm>
#ifndef SSM_BACKEND_ROOT
#define SSM_BACKEND_ROOT "/usr/local/lib/SpiralPlugins"
#endif
namespace Spiral
{
	static std::string defaultAudio= "dummy", defaultDestination= "default";
	void SetAudioBackendDefaults(const std::string &name, const std::string &destination)
	{
		defaultAudio= name.empty() || name == "none" ? "dummy" : name;
		defaultDestination= destination.empty() ? "default" : destination;
	}
	std::string DefaultAudioBackend()
	{
		return defaultAudio;
	}
	std::string DefaultAudioDestination()
	{
		return defaultDestination;
	}
	BackendRegistry::BackendRegistry(const std::string &kind)
	{
		const char *env= std::getenv("SSM_BACKEND_PATH");
		std::string paths= env ? env : SSM_BACKEND_ROOT;
		size_t start= 0, end;
		do
		{
			end= paths.find(':', start);
			std::string path= paths.substr(start, end - start);
			if(!path.empty())
				Scan(path + "/" + kind, kind);
			start= end + 1;
		} while(end != std::string::npos);
	}
	void BackendRegistry::Scan(const std::string &path, const std::string &kind)
	{
		DIR *dir= opendir(path.c_str());
		if(!dir)
			return;
		std::vector<std::string> files;
		dirent *entry;
		while((entry= readdir(dir)))
		{
			std::string n= entry->d_name;
			if(n.size() > 3 && n.substr(n.size() - 3) == ".so")
				files.push_back(n);
		}
		closedir(dir);
		std::sort(files.begin(), files.end());
		for(size_t i= 0; i < files.size(); ++i)
		{
			void *h= dlopen((path + "/" + files[i]).c_str(), RTLD_NOW | RTLD_LOCAL);
			if(!h)
				continue;
			typedef const BackendDescriptor *(*Get)();
			Get get= (Get)dlsym(h, "SSM_Backend_v1");
			const BackendDescriptor *d= get ? get() : NULL;
			if(!d || d->ABI != 1 || !d->Kind || kind != d->Kind || !d->Name || !*d->Name || !d->Create || !d->Destroy || Find(d->Name))
			{
				dlclose(h);
				continue;
			}
			handles.push_back(h);
			entries.push_back(d);
		}
	}
	BackendRegistry::~BackendRegistry()
	{
		for(size_t i= handles.size(); i > 0; --i)
			dlclose(handles[i - 1]);
	}
	const BackendDescriptor *BackendRegistry::Find(const std::string &name) const
	{
		for(size_t i= 0; i < entries.size(); ++i)
			if(name == entries[i]->Name)
				return entries[i];
		return NULL;
	}
	std::vector<std::string> BackendRegistry::Names() const
	{
		std::vector<std::string> n;
		for(size_t i= 0; i < entries.size(); ++i)
			n.push_back(entries[i]->Name);
		return n;
	}
} // namespace Spiral
