// Generated by ChatGPT.
#include "BackendModule.h"
#include "DummyAudioBackend.h"
static void *Create(void *c)
{
	return new DummyAudioBackend(((AudioBackendContext *)c)->Host);
}
static void Destroy(void *p)
{
	delete(OutputAudioClientBackend *)p;
}
extern "C" const Spiral::BackendDescriptor *SSM_Backend_v1()
{
	static const Spiral::BackendDescriptor d= {1, "audio", "dummy", Create, Destroy};
	return &d;
}
