// Generated by ChatGPT. Backend modules alone link hardware API libraries.
#include "MidiBackend.h"
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <iostream>
#include <algorithm>
namespace spiralcore
{
	// The dummy is the only compiled-in midi backend.
	static void *CreateDummyMidi(void *) { return static_cast<MidiBackend *>(new DummyMidiBackend); }
	static void DestroyDummyMidi(void *p) { delete static_cast<MidiBackend *>(p); }
	const BackendDescriptor *DummyMidi()
	{
		static const BackendDescriptor d= {SPIRAL_MIDI_PLUGIN_ABI, "midi", "dummy", CreateDummyMidi, DestroyDummyMidi};
		return &d;
	}

	MidiBackendRegistry *MidiBackendRegistry::m_Singleton= NULL;
	MidiBackendRegistry *MidiBackendRegistry::Get()
	{
		if(!m_Singleton)
		{
			m_Singleton= new MidiBackendRegistry;
			m_Singleton->Register(DummyMidi());
		}
		PluginLoader::Get()->RegisterKind(m_Singleton);
		return m_Singleton;
	}
	void MidiBackendRegistry::PackUpAndGoHome()
	{
		if (!m_Singleton || !m_Singleton->CanUnload())
			return;

		PluginLoader::Get()->UnregisterKind(m_Singleton);
		delete m_Singleton;
		m_Singleton= NULL;
	}
	MidiBackendRegistry::MidiBackendRegistry()
	{
	}
	void MidiBackendRegistry::Register(const BackendDescriptor *d)
	{
		if(!d || !d->Kind || std::string(Name()) != d->Kind || !d->Name || !*d->Name || !d->Create || !d->Destroy || Find(d->Name))
			return;
		if(d->ABI != SPIRAL_MIDI_PLUGIN_ABI)
		{
			std::cerr << "midi backend '" << d->Name << "': ABI " << d->ABI
			          << ", host has " << SPIRAL_MIDI_PLUGIN_ABI << "; ignored" << std::endl;
			return;
		}
		entries.push_back(d);
	}
	unsigned MidiBackendRegistry::LoadModules(const std::string &root)
	{
		return PluginLoader::Get()->Load(*this, root);
	}
	bool MidiBackendRegistry::Accept(void *entry, const std::string &)
	{
		const BackendDescriptor *d= ((SpiralPlugin_GetMidiBackendFn)entry)();
		if(!d || !d->Name)
			return false;
		// A compiled-in backend of the same name keeps its place.
		if(Find(d->Name))
			return false;
		Register(d);
		return Find(d->Name) == d;
	}
	void MidiBackendRegistry::Release(void *entry, const std::string &)
	{
		const BackendDescriptor *d = ((SpiralPlugin_GetMidiBackendFn)entry)();
		entries.erase(std::remove(entries.begin(), entries.end(), d), entries.end());
	}

	MidiBackendRegistry::~MidiBackendRegistry()
	{
	}
	const BackendDescriptor *MidiBackendRegistry::Find(const std::string &name) const
	{
		for(size_t i= 0; i < entries.size(); ++i)
			if(name == entries[i]->Name)
				return entries[i];
		return NULL;
	}
	std::vector<std::string> MidiBackendRegistry::Names() const
	{
		std::vector<std::string> n;
		bool dummy= false;
		for(size_t i= 0; i < entries.size(); ++i)
		{
			if(std::string(entries[i]->Name) == "dummy")
				dummy= true;
			else
				n.push_back(entries[i]->Name);
		}
		if(dummy)
			n.push_back("dummy");
		return n;
	}
	MidiBackend *MidiBackendRegistry::Create(const std::string &name)
	{
		const BackendDescriptor *d= Find(name);
		MidiBackend *backend = d ? static_cast<MidiBackend *>(d->Create(NULL)) : NULL;
		if (backend)
			backends[backend] = d;

		return backend;
	}
	void MidiBackendRegistry::Destroy(const std::string &name, MidiBackend *backend)
	{
		std::map<MidiBackend *, const BackendDescriptor *>::iterator found = backends.find(backend);
		if (found == backends.end() || name != found->second->Name)
			return;

		const BackendDescriptor *d = found->second;
		backends.erase(found);
		d->Destroy(backend);
	}
} // namespace spiralcore
