// JACK callback contract with deterministic fake server buffers. Generated by ChatGPT.
#include "JackMidiBackend.cpp"
#include <cassert>
#include <cstring>
#include <iostream>

struct Buffer
{
	unsigned count, capacity;

	Buffer():
	    count(0),
	    capacity(16)
	{
	}

	unsigned char bytes[16][3];
	size_t sizes[16];
};

static Buffer inputBuffer, outputBuffer;
static JackProcessCallback callback;
static void *callbackData;
typedef void (*ShutdownCallback)(void *);
static ShutdownCallback shutdownCallback;
static void *shutdownData;
static bool active = false, fromConnected = false, toConnected = false;
static jack_client_t *fakeClient = reinterpret_cast<jack_client_t *>(1);
static jack_port_t *inPort = reinterpret_cast<jack_port_t *>(2);
static jack_port_t *outPort = reinterpret_cast<jack_port_t *>(3);
extern "C"
{
	jack_client_t *jack_client_open(const char *, jack_options_t, jack_status_t *, ...)
	{
		return fakeClient;
	}

	int jack_client_close(jack_client_t *)
	{
		active = false;
		return 0;
	}

	jack_port_t *jack_port_register(jack_client_t *, const char *, const char *, unsigned long flags, unsigned long)
	{
		return flags == JackPortIsInput ? inPort : outPort;
	}

	int jack_set_process_callback(jack_client_t *, JackProcessCallback f, void *data)
	{
		callback = f;
		callbackData = data;
		return 0;
	}

	void jack_on_shutdown(jack_client_t *, ShutdownCallback f, void *data)
	{
		shutdownCallback = f;
		shutdownData = data;
	}

	void *jack_port_get_buffer(jack_port_t *p, jack_nframes_t)
	{
		return p == inPort ? &inputBuffer : &outputBuffer;
	}

	const char **jack_get_ports(jack_client_t *, const char *, const char *, unsigned long)
	{
		return NULL;
	}

	jack_port_t *jack_port_by_name(jack_client_t *, const char *)
	{
		return NULL;
	}

	int jack_port_is_mine(const jack_client_t *, const jack_port_t *)
	{
		return 0;
	}

	void jack_free(void *) {}

	int jack_deactivate(jack_client_t *)
	{
		active = false;
		return 0;
	}

	int jack_activate(jack_client_t *)
	{
		active = true;
		return 0;
	}

	int jack_port_disconnect(jack_client_t *, jack_port_t *p)
	{
		(p == inPort ? fromConnected : toConnected) = false;
		return 0;
	}

	const char *jack_port_name(const jack_port_t *p)
	{
		return p == inPort ? "SSM:input" : "SSM:output";
	}

	int jack_connect(jack_client_t *, const char *from, const char *)
	{
		(std::strcmp(from, "keys:out") == 0 ? fromConnected : toConnected) = true;
		return 0;
	}

	int jack_port_connected_to(const jack_port_t *p, const char *)
	{
		return p == inPort ? fromConnected : toConnected;
	}

	uint32_t jack_midi_get_event_count(void *b)
	{
		return static_cast<Buffer *>(b)->count;
	}

	uint32_t jack_midi_get_lost_event_count(void *)
	{
		return 0;
	}

	void jack_midi_clear_buffer(void *b)
	{
		static_cast<Buffer *>(b)->count = 0;
	}

	int jack_midi_event_get(jack_midi_event_t *event, void *b, uint32_t index)
	{
		Buffer *buffer = static_cast<Buffer *>(b);
		if (index >= buffer->count)
			return 1;
		event->time = 0;
		event->size = buffer->sizes[index];
		event->buffer = buffer->bytes[index];
		return 0;
	}

	int jack_midi_event_write(void *b, jack_nframes_t time, const jack_midi_data_t *bytes, size_t size)
	{
		Buffer *buffer = static_cast<Buffer *>(b);
		assert(time == 0 && size <= 3);
		if (buffer->count >= buffer->capacity)
			return 1;
		std::memcpy(buffer->bytes[buffer->count], bytes, size);
		buffer->sizes[buffer->count++] = size;
		return 0;
	}
}

int main()
{
	JackMidiTransport transport;
	transport.Open();
	assert(transport.Connect("keys:out", "synth:in") && active && transport.Connected());
	inputBuffer.count = 3;
	inputBuffer.sizes[0] = 3;
	inputBuffer.bytes[0][0] = 0x90;
	inputBuffer.bytes[0][1] = 60;
	inputBuffer.bytes[0][2] = 100;
	inputBuffer.sizes[1] = 2;
	inputBuffer.bytes[1][0] = 0xc1;
	inputBuffer.bytes[1][1] = 7;
	inputBuffer.sizes[2] = 1;
	inputBuffer.bytes[2][0] = 0xf8;
	assert(transport.Write(MidiPacket(0x90, 65, 99)));
	assert(transport.Write(MidiPacket(0xc0, 8)));
	assert(transport.Write(MidiPacket(0xf8)));
	callback(256, callbackData);
	assert(outputBuffer.count == 3 && outputBuffer.sizes[0] == 3 && outputBuffer.sizes[1] == 2 && outputBuffer.sizes[2] == 1);
	assert(outputBuffer.bytes[0][1] == 65 && outputBuffer.bytes[0][2] == 99);
	assert(transport.Flush());
	MidiPacket p;
	assert(transport.Read(p) && p.Status == 0x90 && p.Data1 == 60 && p.Data2 == 100);
	assert(transport.Read(p) && p.Status == 0xc1 && p.Data1 == 7);
	assert(transport.Read(p) && p.Status == 0xf8);
	assert(!transport.Read(p));
	// A full JACK buffer must retain a note-off for the next cycle.
	inputBuffer.count = 0;
	outputBuffer.capacity = 0;
	assert(transport.Write(MidiPacket(0x80, 65, 0)));
	callback(256, callbackData);
	assert(outputBuffer.count == 0);
	outputBuffer.capacity = 16;
	callback(256, callbackData);
	assert(outputBuffer.count == 1 && outputBuffer.bytes[0][0] == 0x80);
	assert(transport.Flush());
	toConnected = false;
	assert(!transport.Connected());
	assert(transport.Connect("keys:out", "synth:in"));
	shutdownCallback(shutdownData);
	assert(!transport.Alive() && !transport.Write(MidiPacket(0x90, 60, 1)));
	transport.Close();
	assert(!active);
	std::cout << "JACK callback input/output, lengths, buffer pressure, disconnect and shutdown PASS\n";
}
