// Native ALSA sequencer MIDI backend. Generated by ChatGPT.
// SPDX-License-Identifier: GPL-2.0-or-later
#include "BackendModule.h"
#include "NativeMidi.h"
#include <alsa/asoundlib.h>
#include <sstream>
#include <stdexcept>
#include <cerrno>
using namespace Spiral;
class AlsaMidiTransport: public MidiTransport
{
	struct Port { std::string name; int client, port; };
	snd_seq_t *seq= NULL;
	snd_midi_event_t *decoder= NULL, *encoder= NULL;
	int input= -1, output= -1, own= -1;
	int srcClient= -1, srcPort= -1, dstClient= -1, dstPort= -1;
	bool lostInput= false;
	std::string status;
	std::vector<Port> sources, destinations;
	void Check(int error, const char *operation)
	{
		if(error >= 0) return;
		status= std::string("ALSA MIDI: ") + operation + ": " + snd_strerror(error);
		throw std::runtime_error(status);
	}
	std::vector<Port> Enumerate(bool out)
	{
		std::vector<Port> result;
		snd_seq_client_info_t *client;
		snd_seq_port_info_t *port;
		snd_seq_client_info_alloca(&client);
		snd_seq_port_info_alloca(&port);
		snd_seq_client_info_set_client(client, -1);
		unsigned required= out ? SND_SEQ_PORT_CAP_WRITE | SND_SEQ_PORT_CAP_SUBS_WRITE :
		                         SND_SEQ_PORT_CAP_READ | SND_SEQ_PORT_CAP_SUBS_READ;
		while(snd_seq_query_next_client(seq, client) >= 0)
		{
			int id= snd_seq_client_info_get_client(client);
			if(id == own || id == SND_SEQ_CLIENT_SYSTEM) continue;
			snd_seq_port_info_set_client(port, id);
			snd_seq_port_info_set_port(port, -1);
			while(snd_seq_query_next_port(seq, port) >= 0)
			{
				unsigned caps= snd_seq_port_info_get_capability(port);
				if((caps & required) != required || (caps & SND_SEQ_PORT_CAP_NO_EXPORT)) continue;
				int number= snd_seq_port_info_get_port(port);
				std::ostringstream name;
				name << id << ':' << number << " " << snd_seq_client_info_get_name(client)
				     << " / " << snd_seq_port_info_get_name(port);
				result.push_back(Port{name.str(), id, number});
			}
		}
		return result;
	}
	bool Subscription(int fromClient, int fromPort, int toClient, int toPort)
	{
		if(fromClient < 0 || toClient < 0) return true;
		snd_seq_port_subscribe_t *sub;
		snd_seq_port_subscribe_alloca(&sub);
		snd_seq_addr_t from= {(unsigned char)fromClient, (unsigned char)fromPort};
		snd_seq_addr_t to= {(unsigned char)toClient, (unsigned char)toPort};
		snd_seq_port_subscribe_set_sender(sub, &from);
		snd_seq_port_subscribe_set_dest(sub, &to);
		return snd_seq_get_port_subscription(seq, sub) >= 0;
	}
public:
	~AlsaMidiTransport() { Close(); }
	void Open()
	{
		Check(snd_seq_open(&seq, "default", SND_SEQ_OPEN_DUPLEX, SND_SEQ_NONBLOCK), "open sequencer");
		Check(snd_seq_set_client_name(seq, "SpiralSynthModular MIDI"), "name client");
		own= snd_seq_client_id(seq);
		input= snd_seq_create_simple_port(seq, "input", SND_SEQ_PORT_CAP_WRITE | SND_SEQ_PORT_CAP_SUBS_WRITE,
		                                 SND_SEQ_PORT_TYPE_MIDI_GENERIC | SND_SEQ_PORT_TYPE_APPLICATION);
		Check(input, "create input");
		output= snd_seq_create_simple_port(seq, "output", SND_SEQ_PORT_CAP_READ | SND_SEQ_PORT_CAP_SUBS_READ,
		                                  SND_SEQ_PORT_TYPE_MIDI_GENERIC | SND_SEQ_PORT_TYPE_APPLICATION);
		Check(output, "create output");
		Check(snd_midi_event_new(256, &decoder), "create decoder");
		Check(snd_midi_event_new(256, &encoder), "create encoder");
		snd_midi_event_no_status(decoder, 1);
		status= "ALSA MIDI ready";
	}
	void Close()
	{
		if(decoder) snd_midi_event_free(decoder);
		if(encoder) snd_midi_event_free(encoder);
		if(seq) snd_seq_close(seq);
		seq= NULL; decoder= encoder= NULL;
		input= output= own= srcClient= srcPort= dstClient= dstPort= -1;
	}
	bool Alive() const { return seq != NULL; }
	std::vector<std::string> Ports(bool out)
	{
		auto &list= out ? destinations : sources;
		list= Enumerate(out);
		std::vector<std::string> names;
		for(const auto &p: list) names.push_back(p.name);
		return names;
	}
	bool Connect(const std::string &src, const std::string &dst)
	{
		if(srcClient >= 0) snd_seq_disconnect_from(seq, input, srcClient, srcPort);
		if(dstClient >= 0) snd_seq_disconnect_to(seq, output, dstClient, dstPort);
		srcClient= dstClient= -1;
		snd_seq_drop_input(seq);
		snd_midi_event_reset_decode(decoder);
		bool inOK= src.empty(), outOK= dst.empty();
		std::string detail;
		for(const auto &p: sources) if(p.name == src)
		{
			int err= snd_seq_connect_from(seq, input, p.client, p.port);
			inOK= err >= 0;
			if(inOK) { srcClient= p.client; srcPort= p.port; }
			else detail= snd_strerror(err);
			break;
		}
		for(const auto &p: destinations) if(p.name == dst)
		{
			int err= snd_seq_connect_to(seq, output, p.client, p.port);
			outOK= err >= 0;
			if(outOK) { dstClient= p.client; dstPort= p.port; }
			else detail= snd_strerror(err);
			break;
		}
		status= !inOK ? "ALSA MIDI source unavailable" : !outOK ? "ALSA MIDI destination unavailable" : "ALSA MIDI ready";
		if(!detail.empty()) status+= ": " + detail;
		return inOK && outOK;
	}
	bool Connected()
	{
		return Subscription(srcClient, srcPort, own, input) && Subscription(own, output, dstClient, dstPort);
	}
	bool Read(MidiPacket &p)
	{
		// Bound work even if an external client floods unsupported/SysEx events.
		for(unsigned n= 0; n < 256; ++n)
		{
			snd_seq_event_t *event= NULL;
			int err= snd_seq_event_input(seq, &event);
			if(err == -EAGAIN) return false;
			if(err == -ENOSPC) { lostInput= true; return false; }
			Check(err, "read sequencer");
			unsigned char bytes[3];
			long count= -1;
			if(event && event->source.client == srcClient && event->source.port == srcPort)
				count= snd_midi_event_decode(decoder, bytes, sizeof(bytes), event);
			if(event) snd_seq_free_event(event);
			if(count > 0 && MidiSize(bytes[0]) == (unsigned)count)
			{
				p= MidiPacket(bytes[0], count > 1 ? bytes[1] : 0, count > 2 ? bytes[2] : 0);
				return true;
			}
		}
		return false;
	}
	bool Write(const MidiPacket &p)
	{
		if(!seq || dstClient < 0 || !ValidMidi(p)) return false;
		unsigned char bytes[]= {p.Status, p.Data1, p.Data2};
		snd_seq_event_t event;
		snd_seq_ev_clear(&event);
		snd_midi_event_reset_encode(encoder);
		if(snd_midi_event_encode(encoder, bytes, MidiSize(p.Status), &event) <= 0 || event.type == SND_SEQ_EVENT_NONE) return false;
		snd_seq_ev_set_source(&event, output);
		// Direct addressing prevents notes being copied to unrelated subscribers.
		snd_seq_ev_set_dest(&event, dstClient, dstPort);
		snd_seq_ev_set_direct(&event);
		return snd_seq_event_output_direct(seq, &event) >= 0;
	}
	bool LostInput() { bool value= lostInput; lostInput= false; return value; }
	std::string Status() const { return status; }
};
static void *Create(void *)
{
	try { return new NativeMidiBackend(new AlsaMidiTransport); }
	catch(...) { return NULL; }
}
static void Destroy(void *p) { delete static_cast<MidiBackend *>(p); }
extern "C" const BackendDescriptor *SSM_Backend_v1()
{
	static const BackendDescriptor d= {1, "midi", "alsa", Create, Destroy};
	return &d;
}
