// Generated by ChatGPT.
#include "BackendModule.h"
#include "MidiBackend.h"
static void *Create(void *)
{
	return new Spiral::DummyMidiBackend;
}
static void Destroy(void *p)
{
	delete(Spiral::MidiBackend *)p;
}
extern "C" const Spiral::BackendDescriptor *SSM_Backend_v1()
{
	static const Spiral::BackendDescriptor d= {1, "midi", "dummy", Create, Destroy};
	return &d;
}
