// Native JACK MIDI backend. Generated by ChatGPT.
// SPDX-License-Identifier: GPL-2.0-or-later
#include "BackendModule.h"
#include "NativeMidi.h"
#include <jack/jack.h>
#include <jack/midiport.h>
#include <algorithm>
#include <stdexcept>
using namespace Spiral;
class JackMidiTransport: public MidiTransport
{
	jack_client_t *client= NULL;
	jack_port_t *input= NULL, *output= NULL;
	MidiQueue incoming, outgoing;
	std::atomic<bool> dead{false}, inputLost{false};
	std::atomic<unsigned> completed{0};
	unsigned submitted= 0;
	bool activated= false;
	std::string source, destination, status;
	static int Process(jack_nframes_t frames, void *self)
	{
		return static_cast<JackMidiTransport *>(self)->Process(frames);
	}
	static void Shutdown(void *self)
	{
		static_cast<JackMidiTransport *>(self)->dead.store(true);
	}
	int Process(jack_nframes_t frames)
	{
		void *in= jack_port_get_buffer(input, frames);
		void *out= jack_port_get_buffer(output, frames);
		jack_midi_clear_buffer(out);
		unsigned count= jack_midi_get_event_count(in);
		if(count > 1024 || jack_midi_get_lost_event_count(in)) inputLost.store(true);
		for(unsigned i= 0; i < std::min(count, 1024u); ++i)
		{
			jack_midi_event_t event;
			if(jack_midi_event_get(&event, in, i) || !event.size) continue;
			unsigned size= MidiSize(event.buffer[0]);
			if(!size || size != event.size) continue;
			MidiPacket p(event.buffer[0], size > 1 ? event.buffer[1] : 0, size > 2 ? event.buffer[2] : 0);
			if(ValidMidi(p) && !incoming.Push(p)) inputLost.store(true);
		}
		MidiPacket p;
		for(unsigned i= 0; i < 256 && outgoing.Peek(p); ++i)
		{
			unsigned char bytes[]= {p.Status, p.Data1, p.Data2};
			// Packets currently have no timestamps: deliver at the next cycle.
			// If full, retain the event (especially note-off) for the next buffer.
			if(jack_midi_event_write(out, 0, bytes, MidiSize(p.Status))) break;
			outgoing.Pop(p);
			completed.fetch_add(1, std::memory_order_release);
		}
		return 0;
	}
	void Fail(const std::string &message)
	{
		status= "JACK MIDI: " + message;
		throw std::runtime_error(status);
	}
	void ClearQueues()
	{
		// Called only with JACK deactivated (or after client_close).
		MidiPacket p;
		while(incoming.Pop(p)) {}
		while(outgoing.Pop(p)) {}
		submitted= 0; completed.store(0);
	}
public:
	~JackMidiTransport() { Close(); }
	void Open()
	{
		dead.store(false);
		jack_status_t result;
		client= jack_client_open("SSM_MIDI", JackNoStartServer, &result);
		if(!client) Fail("server unavailable; start JACK and MIDI will retry");
		input= jack_port_register(client, "input", JACK_DEFAULT_MIDI_TYPE, JackPortIsInput, 0);
		output= jack_port_register(client, "output", JACK_DEFAULT_MIDI_TYPE, JackPortIsOutput, 0);
		if(!input || !output) Fail("cannot register MIDI ports");
		if(jack_set_process_callback(client, Process, this)) Fail("cannot register process callback");
		jack_on_shutdown(client, Shutdown, this);
		status= "JACK MIDI ready";
	}
	void Close()
	{
		if(client) jack_client_close(client); // waits for callbacks to finish
		client= NULL; input= output= NULL; activated= false;
		source.clear(); destination.clear();
		ClearQueues();
	}
	bool Alive() const { return client && !dead.load(); }
	std::vector<std::string> Ports(bool out)
	{
		std::vector<std::string> result;
		const char **names= jack_get_ports(client, NULL, JACK_DEFAULT_MIDI_TYPE, out ? JackPortIsInput : JackPortIsOutput);
		if(names)
		{
			for(unsigned i= 0; names[i]; ++i)
			{
				jack_port_t *p= jack_port_by_name(client, names[i]);
				if(p && !jack_port_is_mine(client, p)) result.push_back(names[i]);
			}
			jack_free(names);
		}
		return result;
	}
	bool Connect(const std::string &src, const std::string &dst)
	{
		if(activated)
		{
			jack_deactivate(client);
			activated= false;
		}
		jack_port_disconnect(client, input);
		jack_port_disconnect(client, output);
		ClearQueues();
		source= src; destination= dst;
		if(jack_activate(client)) Fail("cannot activate client");
		activated= true;
		int inError= src.empty() ? 0 : jack_connect(client, src.c_str(), jack_port_name(input));
		int outError= dst.empty() ? 0 : jack_connect(client, jack_port_name(output), dst.c_str());
		status= inError ? "JACK MIDI source unavailable" : outError ? "JACK MIDI destination unavailable" : "JACK MIDI ready";
		return !inError && !outError;
	}
	bool Connected()
	{
		return Alive() && (source.empty() || jack_port_connected_to(input, source.c_str())) &&
		       (destination.empty() || jack_port_connected_to(output, destination.c_str()));
	}
	bool Read(MidiPacket &p)
	{
		return incoming.Pop(p);
	}
	bool Write(const MidiPacket &p)
	{
		if(!Alive() || !activated || destination.empty() || !ValidMidi(p)) return false;
		if(!outgoing.Push(p)) return false;
		++submitted;
		return true;
	}
	bool Flush()
	{
		// Control/worker thread only. A stopped server must not hang teardown.
		auto deadline= std::chrono::steady_clock::now() + std::chrono::milliseconds(100);
		while(Alive() && completed.load(std::memory_order_acquire) != submitted)
		{
			if(std::chrono::steady_clock::now() >= deadline) return false;
			std::this_thread::sleep_for(std::chrono::milliseconds(1));
		}
		return completed.load(std::memory_order_acquire) == submitted;
	}
	bool LostInput() { return inputLost.exchange(false); }
	std::string Status() const { return dead.load() ? "JACK MIDI server disconnected; retrying" : status; }
};
static void *Create(void *)
{
	try { return new NativeMidiBackend(new JackMidiTransport); }
	catch(...) { return NULL; }
}
static void Destroy(void *p) { delete static_cast<MidiBackend *>(p); }
extern "C" const BackendDescriptor *SSM_Backend_v1()
{
	static const BackendDescriptor d= {1, "midi", "jack", Create, Destroy};
	return &d;
}
