// Generated by ChatGPT. SPDX-License-Identifier: GPL-2.0-or-later
#include "NativeMidi.h"
#include <algorithm>
#include <cstring>
#include <exception>
using namespace Spiral;

NativeMidiBackend::NativeMidiBackend(MidiTransport *t):
    transport(t),
    stop(false),
    reset(false),
    overflow(false),
    ready(false),
    epoch(0),
    status("Starting MIDI")
{
	std::memset(notes, 0, sizeof(notes));
	std::memset(sustain, 0, sizeof(sustain));
	if (pthread_create(&worker, NULL, Worker, this))
		throw std::runtime_error("Cannot start MIDI worker");
}

void *NativeMidiBackend::Worker(void *self)
{
	static_cast<NativeMidiBackend *>(self)->Run();
	return NULL;
}

NativeMidiBackend::~NativeMidiBackend()
{
	stop.store(true);
	pthread_join(worker, NULL);
}

void NativeMidiBackend::Track(const MidiPacket &p)
{
	unsigned channel = p.Status & 15, kind = p.Status & 0xf0;
	if (kind == 0x90 || kind == 0x80)
		notes[channel][p.Data1] = kind == 0x90 && p.Data2;
	if (kind == 0xb0 && p.Data1 == 64)
		sustain[channel] = p.Data2 >= 64;
}

void NativeMidiBackend::Panic()
{
	// Never broadcast All Notes Off to channels shared by another client.
	double deadline = SSMCompat::MonotonicMilliseconds() + 250;
	for (unsigned c = 0; c < 16; ++c)
	{
		if (sustain[c])
		{
			if (!transport->Write(MidiPacket(0xb0 | c, 64, 0)))
			{
				transport->Flush();
				transport->Write(MidiPacket(0xb0 | c, 64, 0));
			}
			sustain[c] = false;
		}
		for (unsigned n = 0; n < 128; ++n)
			if (notes[c][n])
			{
				if (SSMCompat::MonotonicMilliseconds() >= deadline)
				{
					std::memset(notes, 0, sizeof(notes));
					std::memset(sustain, 0, sizeof(sustain));
					return; // A stalled server must not hold up backend destruction.
				}
				if (!transport->Write(MidiPacket(0x80 | c, n, 0)))
				{
					transport->Flush();
					transport->Write(MidiPacket(0x80 | c, n, 0));
				}
				notes[c][n] = false;
			}
	}
	transport->Flush();
}

void NativeMidiBackend::Run()
{
	while (!stop.load())
	{
		try
		{
			transport->Open();
			unsigned active = ~0u, ticks = 250;
			bool connected = false;
			while (!stop.load() && transport->Alive())
			{
				unsigned desired;
				std::string src, dst;
				{
					SSMCompat::Lock lock(mutex);
					src = source;
					dst = destination;
					desired = epoch.load();
				}
				if (active != desired || ++ticks >= 250)
				{
					ticks = 0;
					std::vector<std::string> ins = transport->Ports(false), outs = transport->Ports(true);
					bool lost = !transport->Connected();
					if (active != desired || !connected || lost)
					{
						ready.store(false);
						MidiPacket stale;
						for (unsigned i = 0; i < 1024 && outgoing.Pop(stale); ++i)
						{
						}
						Panic();
						connected = transport->Connect(src, dst);
						active = desired;
						reset.store(true);
						ready.store(connected && !dst.empty());
					}
					SSMCompat::Lock lock(mutex);
					inputs = ins;
					outputs = outs;
					status = transport->Status();
				}
				MidiPacket p;
				if (overflow.exchange(false))
				{
					// Discard the overflowed batch before releasing its notes.
					for (unsigned i = 0; i < 1024 && outgoing.Pop(p); ++i)
					{
					}
					Panic();
				}
				for (unsigned i = 0; i < 256 && outgoing.Pop(p); ++i)
					if (p.Epoch == active && !dst.empty())
					{
						if (transport->Write(p))
							Track(p);
						else
							overflow.store(true);
					}
				for (unsigned i = 0; i < 256 && transport->Read(p); ++i)
				{
					p.Epoch = active;
					if (ValidMidi(p) && !incoming.Push(p))
						reset.store(true);
				}
				if (transport->LostInput())
					reset.store(true);
				SSMCompat::SleepMilliseconds(2);
			}
			Panic();
		}
		catch (const std::exception &e)
		{
			SSMCompat::Lock lock(mutex);
			status = e.what();
		}
		ready.store(false);
		transport->Close();
		std::memset(notes, 0, sizeof(notes));
		std::memset(sustain, 0, sizeof(sustain));
		reset.store(true);
		{
			SSMCompat::Lock lock(mutex);
			inputs.clear();
			outputs.clear();
			if (!stop.load() && transport->Status().size())
				status = transport->Status();
		}
		for (int n = 0; n < 50 && !stop.load(); ++n)
			SSMCompat::SleepMilliseconds(20);
	}
}

std::vector<std::string> NativeMidiBackend::Ports(bool output)
{
	SSMCompat::Lock lock(mutex);
	return output ? outputs : inputs;
}

void NativeMidiBackend::Select(const std::string &s, const std::string &d)
{
	SSMCompat::Lock lock(mutex);
	if (s != source || d != destination)
	{
		ready.store(false);
		source = s;
		destination = d;
		epoch.fetch_add(1);
	}
}

bool NativeMidiBackend::Poll(MidiPacket &p)
{
	if (reset.exchange(false))
	{
		for (unsigned i = 0; i < 1024 && incoming.Pop(p); ++i)
		{
		}
		p = MidiPacket(0xff);
		return true;
	}
	for (unsigned i = 0; i < 1024 && incoming.Pop(p); ++i)
		if (p.Epoch == epoch.load())
			return true;
	return false;
}

bool NativeMidiBackend::Send(const MidiPacket &p)
{
	if (!ValidMidi(p) || !ready.load())
		return false;
	MidiPacket copy = p;
	copy.Epoch = epoch.load();
	if (outgoing.Push(copy))
		return true;
	overflow.store(true);
	return false;
}

std::string NativeMidiBackend::Status()
{
	SSMCompat::Lock lock(mutex);
	return status;
}
