// Generated by ChatGPT.
#include "AudioBackend.h"
#include "DummyClient.h"
#include <cstring>
#include <unistd.h>
using namespace spiralcore;

DummyClient::DummyClient():
    attached(false),
    frames(0),
    rate(0),
    inChannels(0),
    outChannels(0),
    period(0),
    next(0)
{
}
bool DummyClient::Attach(const std::string &, const AudioClientOptions &opt)
{
	Detach();
	if(!opt.BufferSize || !opt.Samplerate)
		return false;
	frames= opt.BufferSize;
	rate= opt.Samplerate;
	inChannels= opt.InChannels;
	outChannels= opt.OutChannels;
	period= (double)frames / rate;
	next= AudioMonotonicTime();
	timing= AudioCycleTiming();
	timing.SampleRate= rate;
	timing.Step= 1.0 / rate;
	timing.Frames= frames;
	timing.Estimated= true;
	timing.Valid= true;
	attached= true;
	return true;
}
void DummyClient::Detach()
{
	attached= false;
}
// Ready once per period, on the deadline rather than after a sleep, so
// the rate holds over time; a bounded wait keeps shutdown prompt.
int DummyClient::WaitForCycle(unsigned milliseconds)
{
	if(!attached)
		return -1;
	const double now= AudioMonotonicTime();
	if(now < next)
	{
		const double remaining= next - now;
		const double limit= milliseconds / 1000.0;
		usleep((useconds_t)((remaining < limit ? remaining : limit) * 1e6));
		if(AudioMonotonicTime() < next)
			return 0;
	}
	// The period presented at next: there is no device, so input and
	// output are "now" with no latency.
	timing.CallbackTime= next;
	timing.InputTime= next;
	timing.OutputTime= next;
	timing.Frame+= frames;
	next+= period;
	// A long stall restarts the schedule instead of catching up forever.
	if(AudioMonotonicTime() > next + period * 8)
		next= AudioMonotonicTime();
	return 1;
}
bool DummyClient::GetCycleTiming(AudioCycleTiming &t) const
{
	if(!attached)
		return false;
	t= timing;
	return true;
}
bool DummyClient::Write(const float *interleaved, unsigned int nframes)
{
	return attached && interleaved && nframes <= frames;
}
bool DummyClient::Read(float *interleaved, unsigned int nframes)
{
	if(!attached || !interleaved || nframes > frames)
		return false;
	memset(interleaved, 0, nframes * inChannels * sizeof(float));
	return true;
}

// * Built in: the backend of last resort registers itself.
static void *Create(void *)
{
	return static_cast<AudioClient *>(new DummyClient);
}
static void Destroy(void *p)
{
	delete static_cast<AudioClient *>(p);
}
const BackendDescriptor *spiralcore::DummyBackend()
{
	static const BackendDescriptor d= {SPIRAL_AUDIO_PLUGIN_ABI, "audio", "dummy", Create, Destroy};
	return &d;
}
